# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: frontend CI/CD

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.12.1
      uses: actions/setup-node@v3
      with:
        node-version: 18.12.1
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    
    - name: S3 Deploy
      run: aws s3 sync ./dist s3://secret-diary-s3-bucket/ --acl bucket-owner-full-control
      env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ap-northeast-2
    - name: Invalidate CloudFront Cache # 새로 리소스를 업데이트할 때 기존 캐시 무효화
      uses: chetan/invalidate-cloudfront-action@master
      env:
        AWS_DISTRIBUTION: ${{ secrets.AWS_DISTRIBUTION_ID }}
        PATHS: '/index.html'
      continue-on-error: true
    
